require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
require File.join(File.dirname(`node --print "require.resolve('react-native-unimodules/package.json')"`), "cocoapods")

platform :ios, '11.0'
target 'HighChartsApp' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'HighChartsAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  #  post_install do |installer|
    #  flipper_post_install(installer)
  #  end
 end

target 'HighChartsApp-tvOS' do
  # Pods for HighChartsApp-tvOS

  target 'HighChartsApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
